# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/Владислав/Desktop/progi/WebServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/Владислав/Desktop/progi/WebServer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Владислав/Desktop/progi/WebServer/CMakeFiles /mnt/c/Users/Владислав/Desktop/progi/WebServer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Владислав/Desktop/progi/WebServer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named server

# Build rule for target.
server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 server
.PHONY : server

# fast build rule for target.
server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/build
.PHONY : server/fast

src/database.o: src/database.c.o
.PHONY : src/database.o

# target to build an object file
src/database.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/database.c.o
.PHONY : src/database.c.o

src/database.i: src/database.c.i
.PHONY : src/database.i

# target to preprocess a source file
src/database.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/database.c.i
.PHONY : src/database.c.i

src/database.s: src/database.c.s
.PHONY : src/database.s

# target to generate assembly for a file
src/database.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/database.c.s
.PHONY : src/database.c.s

src/handle_app.o: src/handle_app.c.o
.PHONY : src/handle_app.o

# target to build an object file
src/handle_app.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/handle_app.c.o
.PHONY : src/handle_app.c.o

src/handle_app.i: src/handle_app.c.i
.PHONY : src/handle_app.i

# target to preprocess a source file
src/handle_app.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/handle_app.c.i
.PHONY : src/handle_app.c.i

src/handle_app.s: src/handle_app.c.s
.PHONY : src/handle_app.s

# target to generate assembly for a file
src/handle_app.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/handle_app.c.s
.PHONY : src/handle_app.c.s

src/http_pars.o: src/http_pars.c.o
.PHONY : src/http_pars.o

# target to build an object file
src/http_pars.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/http_pars.c.o
.PHONY : src/http_pars.c.o

src/http_pars.i: src/http_pars.c.i
.PHONY : src/http_pars.i

# target to preprocess a source file
src/http_pars.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/http_pars.c.i
.PHONY : src/http_pars.c.i

src/http_pars.s: src/http_pars.c.s
.PHONY : src/http_pars.s

# target to generate assembly for a file
src/http_pars.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/http_pars.c.s
.PHONY : src/http_pars.c.s

src/processing_req.o: src/processing_req.c.o
.PHONY : src/processing_req.o

# target to build an object file
src/processing_req.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/processing_req.c.o
.PHONY : src/processing_req.c.o

src/processing_req.i: src/processing_req.c.i
.PHONY : src/processing_req.i

# target to preprocess a source file
src/processing_req.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/processing_req.c.i
.PHONY : src/processing_req.c.i

src/processing_req.s: src/processing_req.c.s
.PHONY : src/processing_req.s

# target to generate assembly for a file
src/processing_req.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/processing_req.c.s
.PHONY : src/processing_req.c.s

src/register_views.o: src/register_views.c.o
.PHONY : src/register_views.o

# target to build an object file
src/register_views.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/register_views.c.o
.PHONY : src/register_views.c.o

src/register_views.i: src/register_views.c.i
.PHONY : src/register_views.i

# target to preprocess a source file
src/register_views.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/register_views.c.i
.PHONY : src/register_views.c.i

src/register_views.s: src/register_views.c.s
.PHONY : src/register_views.s

# target to generate assembly for a file
src/register_views.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/register_views.c.s
.PHONY : src/register_views.c.s

src/server.o: src/server.c.o
.PHONY : src/server.o

# target to build an object file
src/server.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server.c.o
.PHONY : src/server.c.o

src/server.i: src/server.c.i
.PHONY : src/server.i

# target to preprocess a source file
src/server.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server.c.i
.PHONY : src/server.c.i

src/server.s: src/server.c.s
.PHONY : src/server.s

# target to generate assembly for a file
src/server.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/server.c.s
.PHONY : src/server.c.s

src/views.o: src/views.c.o
.PHONY : src/views.o

# target to build an object file
src/views.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/views.c.o
.PHONY : src/views.c.o

src/views.i: src/views.c.i
.PHONY : src/views.i

# target to preprocess a source file
src/views.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/views.c.i
.PHONY : src/views.c.i

src/views.s: src/views.c.s
.PHONY : src/views.s

# target to generate assembly for a file
src/views.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/server.dir/build.make CMakeFiles/server.dir/src/views.c.s
.PHONY : src/views.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... server"
	@echo "... src/database.o"
	@echo "... src/database.i"
	@echo "... src/database.s"
	@echo "... src/handle_app.o"
	@echo "... src/handle_app.i"
	@echo "... src/handle_app.s"
	@echo "... src/http_pars.o"
	@echo "... src/http_pars.i"
	@echo "... src/http_pars.s"
	@echo "... src/processing_req.o"
	@echo "... src/processing_req.i"
	@echo "... src/processing_req.s"
	@echo "... src/register_views.o"
	@echo "... src/register_views.i"
	@echo "... src/register_views.s"
	@echo "... src/server.o"
	@echo "... src/server.i"
	@echo "... src/server.s"
	@echo "... src/views.o"
	@echo "... src/views.i"
	@echo "... src/views.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

